config/routes.rb
Rails.application.routes.draw do
  resources :gossip
  resources :city
  resources :session
  #get 'city/:city_id', to: 'city#show', as: 'show_city'
  get '/', to: 'gossip#index'
  resources :user
  #get 'user/:user_id', to: 'user#show', as: 'show_user'
  get 'team', to: 'static#team'
  get 'contact', to: 'static#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true

	has_many :tags
	belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :password, presence: true, length: { minimum: 6 }
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :age, presence: true, numericality: { only_integer: true }
	validates :city, presence: true
	validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Email adress please" }

	has_many :gossips
	belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/city_controller.rb
class CityController < ApplicationController
	
	def show
    @city = City.find(params[:id])
    
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

  def index # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    @gossips = Gossip.all
  end

  def show # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @gossip = Gossip.find(params[:id])
    @city = City.find(@gossip.user.city_id)
  end

  def new # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)

  end

# Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
# pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
# Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  def create
    @gossip = Gossip.new(user: User.last, title: params[:title], content: params[:content])
    #@gossip.user = User.find_by(id: session[:user_id])
    if @gossip.save
      flash[:success] = "Your gossip has been submitted"
      redirect_to gossip_index_path
    else
      render new_gossip_path
    end
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
  # pour info, le contenu de ce formulaire sera accessible dans le hash params
  # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.permit(:title, :content)
    if @gossip.update(gossip_params)
      flash[:success] = "Your gossip has been updated."
      redirect_to gossip_index_path
    else
    render :edit
    end
  end

  # Méthode qui récupère le potin concerné et le détruit en base
  # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossip_index_path
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # cherche s'il existe un utilisateur en base avec l’e-mail
    user = User.find_by(email: params[:email])

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      # redirige où tu veux, avec un flash ou pas
      redirect_to gossip_index_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      redirect_to gossip_index_path
    end

  end

  def destroy
    session.delete(:user_id)
    redirect_to gossip_index_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team
  end

  def contact
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], city: params[:city], age: params[:age], description: params[:description], password: params[:password])
      if @user.save
        redirect_to gossip_index_path
      else
        render user_new_path
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/city/show.html.erb
<div class="container text-center">
  </br>
  <h1>Gossips from <%= @city.name %> (<%= @city.zip_code %>)</h1>
  </br>
</div>

<div class="card-columns">
  <% @city.users.each do |user| %>
    <%user.gossips.each do |gossip|%>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= gossip.title %></h5>
          <footer class="blockquote-footer"> <%= gossip.user.first_name %></footer></br>
          <p><a class="btn btn-info" <%=link_to "View gossip", gossip_path(gossip.id)%></a></p>
        </div>
      </div>
   <% end %>
  <% end %>
</div>

app/views/gossip/edit.html.erb
<div class='container'>
  </br>
  <%= form_tag url_for(action: 'update'), method: "put" do %>
    <div class='form-group'>
      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', "", class: 'form-control'%>
    </div>
    <div class='form-group'>
      <%= label_tag 'Your gossip' %>
      <%= text_area_tag 'content', "" , class: 'form-control'%>
    </div>
    <%= submit_tag "Edit", class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/gossip/index.html.erb
<div class="jumbotron">
	<div class="container text-center">
        <h1 class="display-3">Welcome to The Gossip Project !</h1>
         <p>Gossiping gives you the power to make other people see the world the way you do.</p>
        <p><a class="btn btn-lg btn-primary" href=<%= new_gossip_path %> role="button">Add your gossip &raquo;</a></p>
    </div>
</div>

<div class="card-columns">
 	<% @gossips.each do |gossip| %>
 		<div class="card">
    	<div class="card-body">
      	<h5 class="card-title"><%= gossip.title %></h5>
      	<footer class="blockquote-footer"> <%= gossip.user.first_name %></footer></br>
    		<p><a class="btn btn-info" <%=link_to "View gossip", gossip_path(gossip.id)%></a></p>
    	</div>
  	</div>
  <% end %>
</div>

app/views/gossip/new.html.erb
<div class="container text-center">
    <div class="form-group">
        <br>
        <h1>Yes, let's gossip !</h1>
        <p>Gossip is conversation that's light, informal, and usually about other people's business. It can be fun to gossip about others, so ENJOY ! </br> (But don't forget: no one likes it when they're the subject of gossip)</p></br>
        <%= form_tag url_for(action: 'create'), method: "post" do %>
        <div class='form-group'>
          <%= label_tag 'Title' %>
          <%= text_field_tag 'title', "", class: 'form-control' %>
    </div>
    <div class='form-group'>
        <%= label_tag 'Your gossip' %>
        <%= text_area_tag 'content', "",  class: 'form-control' %>
    </div>
        <%= submit_tag "Submit", class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/gossip/show.html.erb
<div class="container text-center">
	</br>
	<h1>Gossip n°<%= @id %> </h1><br>

	<div class="card">
   		<h4 class="card-header text-center"><%= @gossip.title%></h4>
	    <div class="card-body">
		    <p class="card-text"><%= @gossip.content%></p>
		    <footer class="blockquote-footer"> <cite> <%=link_to @gossip.user.first_name, user_path(@gossip.user.id)%> from <%=link_to @city.name, city_path(@gossip.user.city.id)%></cite></footer>
		    </br>
					<%= link_to "Edit gossip", edit_gossip_path(@gossip.id), class: "btn btn-secondary" %>
					<%= link_to "Delete gossip", gossip_path(@gossip.id), class: "btn btn-danger", method: :delete, data: { confirm: 'Do you really want to delete it ?' } %>
				<a href=<%= gossip_index_path %> class="btn btn-primary">Back to gossips</a>
	    </div>
	    <div class="card-footer text-muted">
	        <%= @gossip.created_at%>
	    </div>
	 </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" <%=link_to "The Gossip Project", gossip_index_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" <%=link_to "Team", team_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%=link_to "Contact", contact_path %></a>
      </li>
  
    <ul class="navbar-nav my-2 my-lg-0">
      <li class="nav-item">
        <a class="btn btn-outline-success" <%= link_to "login", new_session_path %></a> 
      </li>
      <li class="nav-item">
        <a class="btn btn-outline-success" <%= link_to "Sign up", new_user_path %></a> 
      </li>
    </ul>

      
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/session/new.html.erb
<form>
  <%= form_tag url_for(action: 'create'), method: "post" do %>

    <div class='form-row'>
      <div class="col-md-4 mb-3">
        <%= label_tag 'Email' %>
        <%= text_field_tag 'email', "",  class: 'form-control' %>
      </div>

      <div class="col-md-4 mb-3">
        <%= label_tag 'Password' %>
        <%= text_field_tag 'password', "",  class: 'form-control' %>
      </div>   
    </div>
    
    <%= submit_tag "Sign in", class: 'btn btn-primary' %>

    <% end %>
</form>

app/views/user/new.html.erb
<form class="container">
  <br>
  <h1>Sign up</h1>
  <br>

  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div class='form-row'>
      <div class="col-md-4 mb-3">
        <%= label_tag 'First name' %>
        <%= text_field_tag 'first_name', "", class: 'form-control' %>
      </div>

      <div class="col-md-4 mb-3">
        <%= label_tag 'Last name' %>
        <%= text_field_tag 'last_name', "",  class: 'form-control' %>
      </div>
    
      <div class="col-md-4 mb-3">
        <%= label_tag 'Age' %>
        <%= number_field_tag 'age', "",  class: 'form-control' %>
      </div>

      <div class="col-md-4 mb-3">
        <%= label_tag 'City' %>
        <%= text_field_tag 'city', "",  class: 'form-control' %>
      </div>

      <div class="col-md-8 mb-3">
        <%= label_tag 'Description' %>
        <%= text_area_tag 'description', "",  class: 'form-control' %>
      </div>
    </div>
    
    <div class='form-row'>
      <div class="col-md-4 mb-3">
        <%= label_tag 'Email' %>
        <%= text_field_tag 'email', "",  class: 'form-control' %>
      </div>

      <div class="col-md-4 mb-3">
        <%= label_tag 'Password' %>
        <%= text_field_tag 'password', "",  class: 'form-control' %>
      </div>   
    </div>`
    <%= submit_tag "Submit", class: 'btn btn-primary' %>
  <% end %>
</form>

app/views/user/show.html.erb
<div class="container text-center">
  <br><br>
  <div class="card">
    <div class="card-header">
      <h3><%= @user.first_name %> <%= @user.last_name %></h3>
    </div>
    <div class="card-body">
      <h5 class="card-title">Age : <%= @user.age %></h5>
      <p class="card-text">Email : <%= @user.email %></p>
      <p class="card-text">From : <%= @user.city.name %></p>
      <p class="card-text">Description : <%= @user.description %></p>
      <a href=<%= gossip_index_path %> class="btn btn-primary">Back to gossips</a>
    </div>
</div>